[package]
name = "voting-machine-core"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm-core = { version = "0.10.0", default-features = false, features = ["pure"] }
serde = { version = "1.0", default-features = false }
