[package]
name = "password-checker-methods"
version = "0.1.0"
edition = "2021"

[package.metadata.risc0]
methods = ["guest"]

[profile.release]
lto = true
opt-level = "z"

[build-dependencies]
risc0-build = "0.11"
